# Generated by Django 5.1.2 on 2024-11-11 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_college_college_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='college',
            table='college',
        ),
        migrations.AlterModelTable(
            name='student',
            table='candidate',
        ),
    ]
