# Generated by Django 5.1.2 on 2024-11-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_college_table_alter_student_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='rank',
        ),
        migrations.AlterField(
            model_name='student',
            name='c_name',
            field=models.CharField(max_length=255),
        ),
    ]
