# Generated by Django 5.1.2 on 2024-11-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_remove_student_id_alter_student_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
